version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: bilbot-api:latest
    container_name: bilbot-api
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"
    networks:
      - bilnet

networks:
  bilnet:
    driver: bridge
